### ISSUE TITLE
invalid item in dependencies list

### ISSUE THREAD

**Issue by lyhighfly** [andrei-kuznetsov/android-studio-builder#3]
Env:
CPU: AMD 5950x;
OS: Linux liuyu-pc 5.11.0-25-generic #27~20.04.1-Ubuntu x86_64 GNU/Linux;
Docker:version 20.10.7, build f0df350

Steps:
follow the steps in README.md,build successfully,then import project to IDEA,appears errors like below :

`Module intellij.android.projectSystem.gradle.sync: invalid item 'studio-sdk' in the dependencies list
Module intellij.android.projectSystem.gradle.sync: invalid item 'studio-plugin-junit' in the dependencies list
Module intellij.android.projectSystem.gradle.sync: invalid item 'studio-plugin-Kotlin' in the dependencies list
Module intellij.android.projectSystem.gradle.sync.tests: invalid item 'studio-sdk' in the dependencies list
Module intellij.android.projectSystem.gradle.sync.tests: invalid item 'studio-plugin-Kotlin' in the dependencies list
Module intellij.android.projectSystem.gradle.sync.tests: invalid item 'studio-plugin-junit' in the dependencies list
Module google-cloud-tools-as: invalid item 'studio-sdk' in the dependencies list
Module google-cloud-tools-as: invalid item 'studio-plugin-Kotlin' in the dependencies list
Module google-cloud-tools-as: invalid item 'studio-plugin-gradle' in the dependencies list
Module google-cloud-tools-as: invalid item 'studio-plugin-Groovy' in the dependencies list
Module google-cloud-tools-as: invalid item 'studio-plugin-git4idea' in the dependencies list
Module intellij.android.build-attribution: invalid item 'studio-sdk' in the dependencies list
Module intellij.android.build-attribution: invalid item 'studio-plugin-gradle' in the dependencies list
Module intellij.android.build-attribution: invalid item 'studio-plugin-Kotlin' in the dependencies list
Module intellij.android.build-attribution.tests: invalid item 'studio-sdk' in the dependencies list
Module intellij.android.build-attribution.tests: invalid item 'studio-plugin-Kotlin' in the dependencies list
Module intellij.android.build-attribution.tests: invalid item 'studio-plugin-gradle' in the dependencies list` and so on.

Did you encounter the problem? 
Any ideas? :)

**Comment by andrei-kuznetsov** [comment]
> Did you encounter the problem?

Yes, I did.


> Any ideas?

You have at least 3 options:
1. Ignore (build in IDEA is successful, right?)
2. Create empty project libraries with expected names (e.g. studio-plugin-gradle, ...)
3. Cleanup modules by deleting references to non-existing libraries

IntelliJ IDEA follows approach *3. I didn't include this patch because large patches are hard to maintain and usually they won't be compatible with new studio sources.

**Comment by lyhighfly** [comment]
> > Did you encounter the problem?
> 
> Yes, I did.
> 
> > Any ideas?
> 
> You have at least 3 options:
> 
> 1. Ignore (build in IDEA is successful, right?)
> 2. Create empty project libraries with expected names (e.g. studio-plugin-gradle, ...)
> 3. Cleanup modules by deleting references to non-existing libraries
> 
> IntelliJ IDEA follows approach *3. I didn't include this patch because large patches are hard to maintain and usually they won't be compatible with new studio sources.

After some research, I found the 'IDEA jdk' not be configed, so, added it : Project Structure->Platform Settings->SDKs;
Before rebuild project ,IDEA prompted 'Kotlin Plugin must 1.4.99 or lower', My IDEA is 212, it is not compat with Kotlin Plugin which version is 1.4.99 or lower, I reinstall IDEA-203, but i didn`t found plugin 1.4.99, the version nearest 1.4.99 is 1.4.31,so i did and rebuild project again.Unfortunatly, also encounted error :


`Kotlin: [Internal Error] org.jetbrains.kotlin.codegen.CompilationException: Back-end (JVM) Internal error: Failed to generate expression: KtProperty
File being compiled: (13,3) in /home/liuyu/Downloads/android-studio-builder/aosp_source/tools/idea/platform/execution-impl/src/com/intellij/execution/impl/BeforeRunTaskHelper.kt
The root cause java.lang.IllegalStateException was thrown at: org.jetbrains.kotlin.codegen.state.KotlinTypeMapper$typeMappingConfiguration$1.processErrorType(KotlinTypeMapper.kt:122)
...
...
Caused by: java.lang.IllegalStateException: Error type encountered: [ERROR : <LOOP IN SUPERTYPES>] (ErrorType).
`


I guessed it is still relatived with Kotlin Plugin ,but did`t find anything helpful after googling a lot.
 I wonder whether it exists Kotlin Plugin which version is between 1.4.31 and 1.4.99,or is there  some method work around for building project?

**Comment by andrei-kuznetsov** [comment]
> I found the 'IDEA jdk' not be configed, so, added it

Ah. You are right. I forgot to mention this step. It is explained here: https://github.com/JetBrains/intellij-community/blob/202/README.md#intellij-build-configuration

`1.4.31` should work fine. This exception looks like a bug in kotlin compiler. Please click "build" button again. If it fails with exactly the same error - please try "rebuild project". If error is different - keep trying to build the project via "build" button. Let me know if neither helped. I observe similar error time to time with kotlin compiler 1.4.x while compiling IDEA sources.

**Comment by andrei-kuznetsov** [comment]
Cleanup: closing obsolete issues
