### ISSUE TITLE
Can build android-studio on windows ?

### ISSUE THREAD

**Issue by ligen1996** [andrei-kuznetsov/android-studio-builder#5]
Hello.Sorry to bother you,but I have to say that you just did a very amazing work!!! That's very awsome!!! 
I want to know if you have any idea about how to build android studio on windows. I've been busy with this for a few weeks,but  nothing worked out. It is a great luck to see your amazing work！！ So I see a glimmer of hope. If you have any idea about this, hope you can give some Precious suggestions.

And I have a question, if I follow your steps，deleting some module fileurl ,then I can get right build result on windows?  Because When I build on windows, always meet error about bazel ......

Thanks a lot and very sorry to bother you.

**Comment by andrei-kuznetsov** [comment]
Hi @ligenvin,

I received your e-mail but suggest to keep our discussion here publicly available.

Yes, my colleague was able to use this instruction and successfully build Android Studio on Windows. I'm not using Windows so I can't help you with the proper Docker setup, especially when WSL is used. If you have problems with the bazel - please post error message here. Maybe I can help you.

In most cases you don't need Android Studio. You will not be able to get full Android Studio installation using my scripts anyway. It works only up to the point where you can load sources into IDEA and built them or debug them. Using IDEA Community sources is much easier, it also has the same Android Plugin as Android Studio. In IDEA's `master` branch current version of Android Plugin is EE Canary 9. I always recommend using IDEA sources whenever possible.

If you still sure that you need Android Studio - what is the bazel error you are facing?

**Comment by ligen1996** [comment]
Oh,I'm happy to receive your reply.I used a installed Community Edition IEDA 2022.2.1(not build from source) and download android studio source code (studio-4.1-dev) from their website. When I begin to build this android studio source code,there are some errors about bazel as below shows:
![image](https://user-images.githubusercontent.com/34165392/188866109-02023518-65b7-4c86-b128-1350a806abda.png)

Do you know how to solve this?

**Comment by ligen1996** [comment]
I google it and find some solution，such as [delete bazel dependency](https://android.googlesource.com/platform/tools/idea/+/refs/heads/studio-master-dev/RELEASE.md).But there are still some errors as below shows:
![image](https://user-images.githubusercontent.com/34165392/188879426-18f254fa-615c-47df-a147-23f5d010a627.png)

**Comment by andrei-kuznetsov** [comment]
@ligenvin, it does not work this way. Bazel needs native toolkits (gcc, ndk, android-sdk and so on), and it needs some concrete versions of that toolkits. Also AOSP team does not publish some parts of their repository (e.g. `/tools/vendor/google/android-ndk` or `/prebuilts/studio/sdk`). After deleting private parts (I assume you probably did something like this: https://github.com/andrei-kuznetsov/android-studio-builder/blob/c34cceaca09bd528cf3f10da3c5982f17bd463a1/patches/tools.base.bazel.patch) you also need to recover missing parts. I don't have a list of patches required for `4.1` (Why do you need that old Android Studio?). The earliest I have is for `4.2` (https://github.com/andrei-kuznetsov/android-studio-builder/blob/c34cceaca09bd528cf3f10da3c5982f17bd463a1/patches/runpatches.sh). Besides the patches you'll also need toolkits like gcc-6, g++-6, python3 and others. See https://github.com/andrei-kuznetsov/android-studio-builder/blob/c34cceaca09bd528cf3f10da3c5982f17bd463a1/Dockerfile.

I recommend two things:
1. Forget about official guide. It is not updated for years. Follow my guide, and use Docker to build dependencies with bazel as explained in the readme: https://github.com/andrei-kuznetsov/android-studio-builder/blob/main/README.md . 
3. Don't use `studio-4.1`. Use something more up-to-date. If EE Canary 8 is too new for you, maybe 2021.2.1 will work? https://github.com/andrei-kuznetsov/android-studio-builder/commits/main

**Comment by ligen1996** [comment]
Thanks!
I just follow [Official website tutorials](https://android.googlesource.com/platform/tools/base/+/studio-master-dev/studio.md) ,then the studio-master-dev I download is 4.1.But the newer version of Android Studio is ok for me.I will try what you said.Thanks a lot for your help.

**Comment by andrei-kuznetsov** [comment]
Sure. `studio-master-dev` is dead. They renamed it to `studio-main` a year ago o so.

Just try to follow this guide: https://github.com/andrei-kuznetsov/android-studio-builder/blob/main/README.md . I've spent a few months building compatible environment. I don't think you can easily repeat it on Windows without docker.

**Comment by ligen1996** [comment]
Oh, I see.And I think they should update their document.I just follow their tutorials but met a lot of mistakes. It is so lucky to get your   help. Have a good day!

**Comment by ligen1996** [comment]
Thanks to your outstanding work! I must admit that without your outstanding work, I could not have successfully completed this task. We followed your guide and worked it out! With the help of your work,we finally built Android Studio on Windows as below show:

![We build Android Studio On Windows](https://user-images.githubusercontent.com/34165392/189015603-54ef3874-5384-47c5-ad24-cce9988c2b30.png)

However,we found some problems with our Android Studio.For instance, we found the Android Studio can find a target device (our mobile phone connected to computer),but, when we attempt to  use Android Studio's profiler tool, the profiler tool can not find a target device.Have you ever met this problem？  Can you use the profile tool successfully within your built Android Stuido? 


![image](https://user-images.githubusercontent.com/34165392/189018388-af0cda06-4591-41b2-9cab-a8c7251824c6.png)

**Comment by ligen1996** [comment]
Oh, we have solve this problem,the reaseon is that we lack some packages,so we copy from a preinstalled version of Android Stuido.Thanks again ! Have a good day
