### ISSUE TITLE
how to release the Android studio I have edited

### ISSUE THREAD

**Issue by ligen1996** [andrei-kuznetsov/android-studio-builder#9]
Hello,Sorry to bother you again.
I have followed your method and built android studio on windows.What's more,I have added corresponding features to the Android Studio project. I just want to ask you how to release the android studio, as  the others need to use the features.I'm looking for methods,but no idea. If you have any idea,please leave some suggestions. Thanks a lot

**Comment by ligen1996** [comment]
I do as the release.md in the project
![image](https://user-images.githubusercontent.com/34165392/196705908-54a45552-2184-4d44-8f09-1a80df5c4e03.png)

**Comment by andrei-kuznetsov** [comment]
I don't have any working method to build Android Studio distributive. Sorry.
You can consider patching and building IDEA community instead (https://github.com/JetBrains/intellij-community). It has the same Android Plugin Electric Eel Beta 2 in the `master`.
